# Generated by Django 4.1.7 on 2023-03-19 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaints_users_delete_person_delete_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='pincode',
            field=models.CharField(default='240000', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='state',
            field=models.CharField(default='gggggg', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
