# Generated by Django 4.1.7 on 2023-03-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_complaints_pincode_complaints_state_complaints_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
