# Generated by Django 4.1.7 on 2023-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_complaints_latlong_alter_complaints_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='location',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
